version: '3.7'

services:
  nginx:
    container_name: con_laravel_sample
    # lokasi source code
    build:
      context: ./
      dockerfile: web.dockerfile
    # path untuk source di dalam docker
    volumes:
      - ./:/var/www
    image: webserver_laravel:1.0
    ports:
      - "8070:80"

  #LARAVEL Service
  app:
    container_name: app_laravel_sample
    build:
      context: ./
      dockerfile: app.dockerfile
    image: app_laravel:1.0
    volumes:
      - ./:/var/www


  #MySQL Service
  mysql:
    image: mysql:5.7.29
    container_name: app_laravel_sample_mysql
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    

